# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

# QQ
windowrule = no_initial_focus on, match:class ^(QQ)$
windowrule = workspace 10, match:class ^(QQ)$

# 微信
# 所有 wechat 窗口都分配到 workspace 10
windowrule = no_initial_focus on, match:class ^(wechat)$
windowrule = workspace 10, match:class ^(wechat)$
# 主窗口：只对 title 为“微信”的窗口设置位置和大小
#windowrulev2 = size 683 850, class:^(wechat)$, title:^(微信)$
#windowrulev2 = move 905 38, class:^(wechat)$, title:^(微信)$

# 对非主窗口（排除特定 title）应用无边框/无模糊/无阴影
windowrule = no_blur on, border_size 0, no_shadow on, match:class ^(wechat)$, match:title negative:^(朋友圈|微信|设置|聊天文件|预览|图片和视频)\W*

# 特殊处理“微信发送给...”窗口（这类窗口 title 不是“微信”，但也不该有装饰）
windowrule = no_blur on, border_size 0, no_shadow on, match:class ^wechat$, match:title ^微信发送给$

# 防止 Steam 主窗口干扰游戏
windowrule = float off, no_initial_focus on, match:title ^(Steam)$
windowrule = float off, no_initial_focus on, match:title ^(登录 Steam)$
windowrule = workspace 11, match:title ^(Steam)$  # 把 Steam 固定到隐藏工作区
windowrule = workspace 11, match:title ^(登录 Steam)$  # 把 Steam 固定到隐藏工作区

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
